### ISSUE TITLE
'CurrieTechnologies' was undefined Error

### ISSUE THREAD

**Issue by FernandoGPinto** [Basaingeal/Razor.SweetAlert2#1416] opened 2021-06-03 00:13 UTC
I'm using blazor wasm, registered the sweet alert service in Program.cs, added the sweet alert script below the framework script as indicated and injected the SweetAlertService into a component but when trying to call FireAsync() I'm getting the following exception:

> Microsoft.JSInterop.JSException: Could not find 'CurrieTechnologies.Razor.SweetAlert2.FireSettings' ('CurrieTechnologies' was undefined).
> Error: Could not find 'CurrieTechnologies.Razor.SweetAlert2.FireSettings' ('CurrieTechnologies' was undefined).

I am also unable to inject SweetAlertService into a component without the @using CurrieTechnologies.Razor.SweetAlert2 directive.

**Comment by arivera12** [comment] 2021-06-05 14:14
Did you added the script reference?
`<script src="_content/CurrieTechnologies.Razor.SweetAlert2/sweetAlert2.min.js"></script>`

**Comment by FernandoGPinto** [comment] 2021-06-05 16:28
Yes I did, right under the framework script reference.

**Comment by arivera12** [comment] 2021-06-05 19:04
Hmmm, which version of .net you are using?

**Comment by arivera12** [comment] 2021-06-05 19:07
I have certainly crashed randomly into this error when running under mobile blazor bindings but still don't know if is a bug of mbb deployment or this library...

**Comment by FernandoGPinto** [comment] 2021-06-05 19:55
I'm using .net 5. Worst case scenario, if there is no obvious/easy fix for
this error, I could try and switch to the javascript version.

**Comment by arivera12** [comment] 2021-06-05 20:13
Maybe you can try uploading a repro of this error and give @Basaingeal a chance to take a look?

**Comment by Basaingeal** [comment] 2021-06-09 20:01
Sorry @FernandoGPinto, I'm not able to reproduce this on my own .NET 5 WASM sample project. If you could create a minimal reproduction repo, I could take a look at that as was suggested.

As for `@using CurrieTechnologies.Razor.SweetAlert2`, you're right, you do need that, but you can stick it in your _Imports.razor file to not have to add it in each time.

**Comment by FernandoGPinto** [comment] 2021-06-09 23:09
Hi @Basaingeal, I haven't responded earlier because the error went away without any changes being made and I was trying to figure out whether it was a temporary fluke. It seems that it wasn't and I haven't encountered the error since.

**Comment by arivera12** [comment] 2021-06-10 04:12
@FernandoGPinto maybe you can close this issue then?

**Closed** 2021-06-10 08:16 UTC

**Comment by agust220** [comment] 2022-06-30 12:20
I am having the same problem and @couscousbzh's solution did not work for me. Any other ideas?

> Could not find 'CurrieTechnologies.Razor.SweetAlert2.FireSettings' ('CurrieTechnologies' was undefined).
Error: Could not find 'CurrieTechnologies.Razor.SweetAlert2.FireSettings' ('CurrieTechnologies' was undefined).
    at https://localhost:7019/_framework/blazor.server.js:1:497
    at Array.forEach (<anonymous>)
    at i.findFunction (https://localhost:7019/_framework/blazor.server.js:1:465)
    at E (https://localhost:7019/_framework/blazor.server.js:1:2606)
    at https://localhost:7019/_framework/blazor.server.js:1:3494
    at new Promise (<anonymous>)
    at kt.beginInvokeJSFromDotNet (https://localhost:7019/_framework/blazor.server.js:1:3475)
    at https://localhost:7019/_framework/blazor.server.js:1:72001
    at Array.forEach (<anonymous>)
    at kt._invokeClientMethod (https://localhost:7019/_framework/blazor.server.js:1:71987)

The code (the error occurs at line 231):
![error](https://user-images.githubusercontent.com/9974682/176675523-76a95d87-94c3-46dc-bfa7-0499d192951f.png)

**Comment by theneocosmic** [comment] 2023-07-25 00:43
For me, this error is present in Chrome but in Edge works fine

**Comment by theneocosmic** [comment] 2023-07-25 20:24
I was able  to solve this problem. Solution: Add "defer" keyword at script line. Now, it works fine in Chrome and Edge

<script src="_content/CurrieTechnologies.Razor.SweetAlert2/sweetAlert2.min.js" defer></script>
